### ISSUE TITLE
Naming conflict

### ISSUE THREAD

**Issue by bsideup** [springtainer/springtainer-common#28]
Hi!

It seems that you're doing something **very** similar to http://testcontainers.org. I have two questions for you:
1. Have you considered using Testcontainers as the underlying "engine"?
1. Do you mind changing the project's name to avoid a confusion because people will think that you're using Testcontainers under the hood.

Thanks!

**Comment by julian-eggers** [comment]
Hi,

first of all: we renamed the project to avoid confusions.
Two years ago we tried the playtika-implementation but it was slow and unstable. After that we started our own implementation, which is very fast and easy to maintain.

**Comment by bsideup** [comment]
Thank you for renaming!

P.S. I would recommend giving Testcontainers another try ;) You can also use the java version directly without the Playtika's Spring Boot support :)
